import {Metadata} from "next"
import {Container} from "@/shared/components/shared/container"
import {Suspense} from "react"
import {Header} from "@/shared/components/shared/header"

export const metadata: Metadata = {
    title: 'Next Pizza | Корзина',
    description: 'Generated by create next app',
}

export default function CheckoutLayout({children}: { children: React.ReactNode }) {
    return (
        <main className={'min-h-screen bg-[#F4F1EE]'}>
            <Container>
                <Suspense>
                    <Header hasSearch={false} hasCart={false} className={'border-none'}/>
                </Suspense>
                {children}
            </Container>
        </main>
    )
}